version: '3.7'
services:
  mongo-db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    networks:
      - common

  server:
    build: # node-express-server
      context: ./node-express-server
      dockerfile: ./Dockerfile
    container_name: mean_backend
    ports:
      - '3000:3000'
    links:
      - mongo-db
    networks:
      - common

  client:
    build: # angular-14-app
      context: ./angular-14-app
      dockerfile: ./Dockerfile
    container_name: mean_frontend
    ports:
      - '8080:4200'
    networks:
      - common
    volumes:
      - ./angular-14-app:/app
    command: npm run start

networks:
  common: